### ISSUE TITLE
IPv6: If a box has multiple IPv6 addresses, should we try all of them?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/rtcweb-transport#14]
Some systems keep old IPv6 addresses around even when changing to new for privacy.

How should we avoid trying the ones that don't make sense to try?

**Comment by nils-ohlmeier** [comment]
As documented here: https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1542523
and here: https://bugzilla.gnome.org/show_bug.cgi?id=761740
it appears that the implementers claim everything is working as designed on systems which accumulate several temporary deprecated IPv6 addresses.

My assumption here is that using deprecated temp addresses as ICE candidates (additionally to the non deprecated temporary address) is not going to increase the likeliness of establishing a connection. So adding these additional ICE candidates only causes extra over head.

Therefore adding a warning/clarification statement for implementers to avoid deprecated temporary IPv6 addresses (in case there is usable non-deprecated temporary IPv6 address available) seem appropriate.

**Comment by alvestrand** [comment]
Adding warning in -12: "If some of the temporary IPv6 addresses, but not all, are marked deprecated, the client SHOULD discard the deprecated addresses."

**Comment by nils-ohlmeier** [comment]
Sounds good to me.

**Comment by alvestrand** [comment]
Addressed in #15 (version -12)
