### ISSUE TITLE
Reference TURN auto-discovery and RETURN?

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/rtcweb-transport#42]
From Andy Hutton (raised 20-22 June 2016):

There is still the issue of what to say in section 3.4 about auto-discovery of TURN servers and the conflicts between application provided, auto discovered, and configured TURN servers.

Section 3.4 currently includes the statement "WebRTC browsers MUST support configuration of STUN and TURN servers, both from browser configuration and from an application".

Previously I suggested the text:

"WebRTC browsers MUST support configuration of STUN and TURN servers, both from browser configuration and from an application. WebRTC browsers MAY also discover TURN servers using TURN Auto-Discovery [draft-ietf-tram-turn-server-discovery]. To resolve conflicts between TURN servers provided by configuration, auto-discovery, and the application WebRTC browsers MAY implement the procedures specified in Recursively Encapsulated TURN (RETURN) [draft-ietf-rtcweb-return]”.

This suggestion was based on the fact that the -return- draft is I believe the only place where there is a statement about what to do about the conflict between application provided and locally configured TURN servers.

**Comment by md84419** [comment]
Agree.  I've additionally proposed that Andy's final sentence is changed to a SHOULD (RECOMMEND):

"To resolve conflicts between TURN servers provided by configuration, auto-discovery, and the application WebRTC browsers are RECOMMENDED to implement the procedures specified in Recursively Encapsulated TURN (RETURN) [draft-ietf-rtcweb-return]"

**Comment by alvestrand** [comment]
WG chairs decision:

Howdy,

Andy Hutton raised an issue with draft-ietf-rtcweb-transports that was considered during the IESG process (this is github issue 42).  When the subject of configuration was discussed, the chairs did not see consensus for a normative requirement to support RETURN at this stage. 

We have therefore recommended that the documents only note the existence of RETURN in the relevant RFC editor note or update.

regards,

Ted, Sean, Cullen

**Comment by alvestrand** [comment]
Added text in -16:

Note that there is other work around STUN and TURN server discovery and management, including [discovery] for server discovery, as well as [return].
