### ISSUE TITLE
Correct name of httpbis-tunnel header

### ISSUE THREAD

**Issue by alvestrand** [rtcweb-wg/rtcweb-transport#6]
The HTTPBIS WG changed the name of this header from "Connect:" to "ALPN:".

This document should either follow suit or stop referring to the header by name.

https://tools.ietf.org/html/draft-ietf-rtcweb-transports-09#ref-I-D.ietf-httpbis-tunnel-protocol

**Comment by andyhutton** [comment]
The tunnel-protocol draft is now an RFC http://tools.ietf.org/html/rfc7639

**Comment by alvestrand** [comment]
Resolved in -10 version.
